### PR TITLE
Added PKCS12 support for user-cred, fixes #48

### PR DESCRIPTION
**Pull request by arax**
- Works on Ruby 1.8.7 - 1.9.3, tested
- Doesn't work on jRuby since it doesn't have a full
  implementation of OpenSSL::PKCS12
- Detects PKCS12 credentials automatically based on
  the file suffix 'p12' (e.g., ~/.globus/usercred.p12)

### CODE REVIEW

**Comment by ffeldhaus** [comment]
Could we use the patch provided here https://github.com/jruby/jruby-ossl/issues/8 to add PKCS12 support for jRuby?

**Comment by arax** [comment]
Unfortunately not, that is the PKCS12 impl already available in jRuby 1.7.2 and it is not enough to actually use PKCS12 credentials only to create them from PEMs. We would need a full impl matching http://www.ruby-doc.org/stdlib-1.9.3/libdoc/openssl/rdoc/OpenSSL/PKCS12.html#method-c-new  :(

**Comment by arax** [comment]
Investigating the use of `java.security.KeyStore` http://docs.oracle.com/javase/6/docs/api/java/security/KeyStore.html directly in jRuby ...

**Comment by ffeldhaus** [comment]
I'd propose that we merge this pull request and handle the jRuby issue in a separate pull request.

**Comment by arax** [comment]
I agree.

**Pull request merged**
