### PR TITLE
Core updates

### PR DESCRIPTION
**Pull request by ffeldhaus**
I updated some core functionality, mainly regarding kinds and mixins now being full objects instead of type identifiers in entities. Also the model handling was slightly improved. Now, if a model is added to a collection, all entities in it will be updated with the kinds and mixins from that model. Thus it is now easier to have more than one model and also to access kind and mixin information through the entity itself.

### CODE REVIEW

**Comment by arax** [comment]
Just a small typo in lib/occi/infrastructure/resource_tpl.rb, everything else works nicely.

https://gist.github.com/3982249

**Comment by ffeldhaus** [comment]
I just found a general issue with handling mixins while fixing the problem. I would like to solve that problem before merging this pull request.

**Comment by ffeldhaus** [comment]
The category issues have been solved. The rOCCI core components are in a good shape now. If there are no objections, I'd like to merge the changes soon and then continue writing rspec tests to ensure a robust core and no problems with the client.

**Comment by ffeldhaus** [comment]
I just pushed the last changes and besides having too few rspec tests as always, I think this is ready to merge. Could you please have a look if everything still works? Especially the last commit splitted the parse method into two methods, which I already replaced everywhere I could find it.

**Pull request merged**
